device: "cuda"
train_seed: 1
model_name: "mistralai/Mistral-7B-Instruct-v0.1"
tokenizer_name: "mistralai/Mistral-7B-Instruct-v0.1"
data_name: "OpenAssistant/oasst1"
peft_config:
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
  lora_dropout: 0.5
  alpha: 16
  r: 16
dpo:
  learning_rate: 5.0e-5
  batch_size: 2
  grad_accum: 4
  warmup_steps: 50
  epochs: 1
  scheduler: "cosine"
  optim: "paged_adamw_32bit"
  max_seq_length: 512
  max_prompt_length: 512
output_dir: "."
sft:
  learning_rate: 5.0e-5
  batch_size: 2
  grad_accum: 4
  warmup_steps: 30
  weight_decay: 0.001
  epochs: 1
  scheduler: "cosine"
  optim: "paged_adamw_32bit"
  max_seq_length: 512
iterations: 3
new_prompts_num: 2
num_responses: 2
proportion: 0.7
data_file: "data.jsonl"